/*
 * This source file was generated by the Gradle 'init' task
 */
package rpg;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
//        Type type = new TypeToken<Character>(){}.getType();
//        Character ch = (Character)Json.getMapfromJson(type, "/datas/character.json");
//        System.out.println(ch);

        //Type type = new TypeToken<HashMap<String, Character>>(){}.getType();
        //HashMap<String, Character> map = (HashMap<String, Character>)Json.getMapfromJson(type, "/dic/characters.json");
        //System.out.println(map);
        Adventure.initialize("/map/vol.1");
        System.out.println("let's start!");

        Adventure.start("冒険の書・第一章");
        System.out.println("end");
    }
}
